default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: kashiraku_development

test:
  <<: *default
  database: kashiraku_test

production:
  primary: &primary_production
    <<: *default
    database: kashiraku_production
    username: kashiraku
    password: <%= ENV["KASHIRAKU_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: kashiraku_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kashiraku_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kashiraku_production_cable
    migrations_paths: db/cable_migrate
